EditBuffer is now also changed if part label was changed, closes #2219
nonlinear-labs-dev/C15 pull request #2222
Opened 2020-10-01 09:44 UTC by schlenkibus

2020-10-01 10:00 UTC, MatthiasSeeber requested changes
- [ ] The star does not appear to be reflected in the WebUI. The Boled is okay.
- [x] The Ticket also mentions the need for a Part Label Rename mechanism in the WebUI --> separate ticket?

2020-10-01 14:58 UTC, hhoegelo commented on projects/epc/playground/src/presets/EditBuffer.cpp
> +  return false;
What, if the original preset was a single sound, than the edit buffer was converted to a dual sound, than the part name was changed? Is this a relevant use case?

2020-10-01 16:35 UTC, hhoegelo commented on projects/epc/playground/src/presets/EditBuffer.cpp
> +  return false;
I agree, that the problem I commented on has no effect for the current users of the method. 

Still it is a problem if we have a method where the name does not reflect the implementation. So either we should rename or at least comment the method to indicate to future users the lack of correctness.

2020-10-06 12:15 UTC, schlenkibus commented on projects/epc/playground/src/presets/EditBuffer.cpp
> +  return false;
I removed the assumption about the source preset, and the labels are compared without checking if the source preset is dual. The current users of this function are already checking for sound types. IMO this function now does what it states it does.

2020-10-06 13:30 UTC, MatthiasSeeber approved these changes

2020-10-07 06:21 UTC, hhoegelo commented on projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/dataModel/DataModelEntity.java
> +		forceNotify = n;
This doesn't look necessary to me - let's talk about it later today.

2020-10-07 09:29 UTC, hhoegelo approved these changes

2020-10-07 09:29 UTC, merged