Issue 2238
nonlinear-labs-dev/C15 pull request #2244
Opened 2020-10-13 16:46 UTC by schlenkibus

closes #2238

2020-10-15 17:35 UTC, MatthiasSeeber requested changes
Since the Editor feature will be subject of a forthcoming PR, the following things may be included there. So far I found the following.

**Sound Check**
No issues found - seems to work properly, incl. Modulation of Split Point.

**Display Issues**
- [ ] the Icon for the Fade Editor moves slightly to the left when clicking on it, I think it should stay where it is?
- [ ] when I use a window width of around 960px, the only visible part of the editor is the piano, values and icons are not visible anymore (as the piano doesn't resize)
- [ ] [Layer] the Fade Range values round the decimal away (see/compare to corresponding Boled)
- [ ] [Layer] the colored areas seem wrong to me. If I set Fade From [I] to C1, C1 should be behind the blue area. If I set Fade From[II] to C6, C6 should be behind the orange area.The shown value of a Fade From indicates the last key on full level, before the fade begins, it has to be included.

**Other Issues**
- [ ] dragging on value fields is really odd. sometimes something happens, but either the "anfasser" focus changes (sometimes not focussing on the value I drag on), or the value simply jumps to minimum/maximum. changing a particular value item smoothly was not possible for me. if drag on values is on the to-implement checklist, maybe also include double click for default - if not, all mouse events on values should be disabled.
- [ ] [Layer] dragging the "anfasser" of a Fade Range can cause jumping behavior (maybe due to rounding of decimals?)
- [ ] consider having a Split or Layer sound and opening the Fade editor. then load a Single preset. I think, in this case the editor should disappear and show the sound tab instead. (For Split and Layer sounds, the editor can stay open i.m.o.)

2020-10-20 13:30 UTC, MatthiasSeeber approved these changes

2020-10-21 06:09 UTC, hhoegelo commented on projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
> +		p.value.value.setValue(clippedValue);
I am not 100% that this is correct. Aren't there use cases where it is temporarily desired to accept values outside the range and in between the quantization steps? For example when using modulation? This has to be tested very carefully.

2020-10-21 06:13 UTC, hhoegelo commented on projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/fadeeditor/KeyBed.java
> +    enum SelectedAnfasser {
Consider renaming to 'SelectedHandle'

2020-10-21 08:27 UTC, schlenkibus commented on projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/useCases/EditBufferUseCases.java
> +		p.value.value.setValue(clippedValue);
I removed this lines again, as i could not recall the reason for adding them in the first place.

2020-10-21 08:28 UTC, schlenkibus commented on projects/epc/web-ui/src/main/java/com/nonlinearlabs/client/world/overlay/belt/fadeeditor/KeyBed.java
> +    enum SelectedAnfasser {
Done, all occurrences of Anfasser are now Handle :/

2020-10-21 13:16 UTC, hhoegelo approved these changes

2020-10-21 13:16 UTC, merged