Issue 2241
nonlinear-labs-dev/C15 pull request #2255
Opened 2020-10-27 17:30 UTC by schlenkibus

closes #2241

2020-10-27 17:52 UTC, MatthiasSeeber requested changes
- [ ] The Split Point enable/disable Sync icon (WebUI - Parameter Belt) doesn't update the Parameter Screen (Boled)
- [ ] the Boled's Overlap icon doesn't disappear completely when syncing from the WebUI (1px column remains)

2020-10-28 07:24 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/controls/PNGControl.cpp
> +          fb.setColor(nearestColorForGrey(greyRaw));
Performing a search in the 'colors'-vector for each pixel seems less than optimal performance wise. I'd suggest to map the colors on import. 'useImageColors()' and 'setColor()' would trigger a re-import than. In loadImage, you could first load the image from file, than loop over all the pixel and apply the transformation once, so that in redraw you can rely on the pixels having only supported values.

2020-10-28 07:26 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/menu/menu-items/SplitSyncItem.h
> +  sigc::connection m_connection;
m_connection is not needed, as you use sigc::mem_fun() in a 'trackable'

2020-10-28 10:53 UTC, MatthiasSeeber approved these changes

2020-10-28 12:14 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/menu/menu-items/SplitSyncItem.h
> +  sigc::connection m_connection;
It says "resolved" but is not, is it?

2020-11-11 08:40 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/menu/menu-items/SplitSyncItem.h
> +  sigc::connection m_connection;
m_connection is still there or am I too stupid to use github?

2020-11-11 09:26 UTC, schlenkibus commented on projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/menu/menu-items/SplitSyncItem.h
> +  sigc::connection m_connection;
still here, and not yet resolved, i will fix this as well

2020-11-11 12:07 UTC, hhoegelo approved these changes

2020-11-11 12:07 UTC, merged