issue-2253
nonlinear-labs-dev/C15 pull request #2256
Opened 2020-10-28 10:03 UTC by schlenkibus

added check if preset message changed before sending same message again. closes #2253

- [ ] todo test

2020-10-28 10:38 UTC, MatthiasSeeber requested changes
> Preset Messages müssen versendet werden, wenn: der User ein Preset oder einen Part lädt (Recall) oder einen Sound konvertiert/randomisiert/initialisiert.
> Sie müssen/sollten nicht versendet werden, wenn ein Sound als Preset abgespeichert wird (Store append/overwrite/insert).

2020-10-28 12:10 UTC, hhoegelo approved these changes

2020-11-03 04:24 UTC, schlenkibus commented
I extracted the use cases for Store Actions from all over the codebase into one central location, now store actions called from the webui and the boled will run the same code. The original issue of sending preset messages when stored is now fixed. Every store will update the selection and loaded preset status to the just inserted, appended preset.

2020-11-03 11:23 UTC, MatthiasSeeber approved these changes
I observed that Presets are only sent to the AudioEngine only when needed - all Store process are "mute" now. Out of curiosity, I have two additional questions.

2020-11-03 11:23 UTC, MatthiasSeeber commented on projects/epc/playground/src/presets/Bank.cpp
> +  getEditBuffer()->undoableLoad(transaction, newPreset, false);
I noticed that in [426, 453], the `getPresetManager()->onPresetStored(newPreset);` is invoked. Why isn't it called here?

2020-11-03 11:23 UTC, MatthiasSeeber commented on projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.h
> +  void thawParameterMessages(bool send);
The name is rather confusing to me. What does `thaw` mean?

2020-11-04 07:38 UTC, hhoegelo commented on projects/epc/playground/src/presets/Bank.cpp
> +  getEditBuffer()->undoableLoad(transaction, newPreset, false);
Good question, I'd like to know that, too. @schlenkibus ?

2020-11-04 07:46 UTC, hhoegelo commented on projects/epc/playground/src/proxies/audio-engine/AudioEngineProxy.h
> +  void thawParameterMessages(bool send);
It is just the opposite of 'freeze' - maybe 'pause' and 'resume' would be more appropriate words. 
Pausing the hundreds of parameter messages makes sense, if we know that eventually there will be a full preset message anyway. 
The wording is borrowed from glib: https://developer.gnome.org/glibmm/stable/classGlib_1_1ObjectBase.html#a1bd8ea7bd8c4084ade6b3c27dddf06a4

2020-11-11 08:38 UTC, hhoegelo commented on projects/epc/playground/src/presets/PresetManager.cpp
> +  m_presetStoreHappened.deferedSend(storedPreset);
It is not actually a problem, because due to our undo logic a preset will 'never' be deleted, but I don't like the idea of deferred signaling of an object by pointer. Theoretically it is possible that the preset is already deleted at the time the signal notification eventually happens. Also, the - so far - one and only user of the signal doesn't care about the preset pointer. So I suggest to remove the pointer and just signal that "some preset store has happened".

2020-11-11 09:25 UTC, schlenkibus commented on projects/epc/playground/src/presets/PresetManager.cpp
> +  m_presetStoreHappened.deferedSend(storedPreset);
makes sense, i will implement your suggestion

2020-11-11 12:08 UTC, hhoegelo approved these changes

2020-11-11 12:09 UTC, merged