Refactor and rework Split/Fadepoint editors
nonlinear-labs-dev/C15 pull request #2359
Opened 2020-12-09 08:34 UTC by hhoegelo

2020-12-09 13:04 UTC, MatthiasSeeber requested changes
- the "Anfassers" not exactly following the mouse cursor position is an inconvenience I could live with, but it certainly is not optimal and I can imagine that some users may voice complaints about that (whether or not this should be fixed immediately is another question)
- [x] in Split sounds, there still is an issue:
![Screenshot from 2020-12-09 14-01-19](https://user-images.githubusercontent.com/37212609/101633348-61919b00-3a27-11eb-88a8-4fcb36353152.png)
These are the initial (synced) Split Point settings. The indication of Part I is wrong, it should cover the black F#3 key as well

2020-12-09 14:35 UTC, schlenkibus commented
> * the "Anfassers" not exactly following the mouse cursor position is an inconvenience I could live with, but it certainly is not optimal and I can imagine that some users may voice complaints about that (whether or not this should be fixed immediately is another question)
> * [x]  in Split sounds, there still is an issue:
>   ![Screenshot from 2020-12-09 14-01-19](https://user-images.githubusercontent.com/37212609/101633348-61919b00-3a27-11eb-88a8-4fcb36353152.png)
>   These are the initial (synced) Split Point settings. The indication of Part I is wrong, it should cover the black F#3 key as well

The issue with default Splitpoint CPs seems to be fixed.
But the mouseposition and "Anfasser" discrepancy is very noticable on my UHD (1440p) Monitor. I would like to see that fixed, if possible.

2020-12-09 14:36 UTC, schlenkibus requested changes
See my comment above.

2020-12-09 17:09 UTC, KlausStrohhaecker commented
Somewhat relatetd, see also https://github.com/nonlinear-labs-dev/C15/issues/2365 for an alternate way of setting a splitpoint (or whatever) by actually pressing a keybed key.

2020-12-10 08:20 UTC, hhoegelo commented
I found some issues and now everything seems to work (on my machine ;-) )

2020-12-10 09:15 UTC, MatthiasSeeber approved these changes

2020-12-10 09:15 UTC, MatthiasSeeber commented on projects/epc/playground/src/parameters/SplitPointParameter.h
> + *    Display Value     |          |
nomencalture: these are rather raw values or key numbers than display values.

2020-12-10 10:20 UTC, schlenkibus approved these changes

2020-12-10 10:20 UTC, merged