Issue 2495
nonlinear-labs-dev/C15 pull request #2542
Opened 2021-03-24 15:28 UTC by schlenkibus

2021-04-06 09:48 UTC, AntonSchmied commented
Since Stephan is testing on a NUC 10i3, the latest changes on "unstable" are important, especially #2541, which ensures that amixer is set to 100% once the audio-engine services starts. The approach we used so far unfortunately only works for older NUCs.

2021-04-09 10:13 UTC, MatthiasSeeber requested changes

2021-04-09 10:13 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/input/InputEventStage.cpp
> +        }
Unfortunately, a `MIDI::PitchBend` Message will still affect the `HW::Bender` regardless of the Mapping (when the Bender is set to a `MSB/LSB CC`, the CC will correctly change the Bender, but the `PitchBend` will still do so as well).
In order to prevent this, I would suggest to encapsulate `onHWChanged` by another check to be sure that the PitchBend Message is allowed to affect the Bender:

`if(m_options->getBenderMSBCC().first == false) // only if Bender setting matches Pitchbend`
`{`
`onHWChanged(4, decoder->getValue(), DSPInterface::HWChangeSource::MIDI);`
`}`

2021-04-09 11:56 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/input/MIDIDecoder.cpp
> +  const auto isSwitching = controlChangeID > 65 && controlChangeID < 70;
- [x] `isMSB` is correct: Ctrl ID is within [1 .. 31] Range
- [ ] `isLSB` is incorrect: Ctrl ID is within [33 .. 63] Range, so `controlChangeID > 32 && controlChangeID < 64` applies
- [ ] `isSwitching` is incorrect: Ctrl ID is within [64 .. 69] Range, so `controlChangeID > 63 && controlChangeID < 70` applies

2021-04-09 12:07 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/input/MIDIDecoder.cpp
> +      hwResult.undecodedValueBytes = { static_cast<uint8_t>(_data1 > 64 ? 127 : 0), 0 };
Our "Switch Condition" is: **0** (for x < 0.5) or **1** otherwise. The **64** means exactly 0.5, so the current implementation does **0** (for x <= 0.5) or **1** otherwise. I'd prefer identical Switch Conditions for Receivev and Send an would like to change this test to:
`...(_data1 > 63 ? 127 : 0)...`

2021-04-13 11:51 UTC, MatthiasSeeber approved these changes

2021-04-15 13:55 UTC, MatthiasSeeber approved these changes

2021-04-15 13:55 UTC, merged