fix usage of ARM Neon extensions
nonlinear-labs-dev/C15 pull request #2545
Opened 2021-03-25 16:06 UTC by hhoegelo

make code compile on arm

2021-03-30 12:08 UTC, MatthiasSeeber requested changes

2021-03-30 12:08 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/C15Synth.cpp
> +#endif
My shallow interpretation of this new Target-based handling of denormal Floats is that:

- either, the ARM solution somehow magically cancels denormal Floats anyway
- or, the ARM solution doesn't provide any comparable "simple" way of getting rid of denormal Floats (like the Intel solution does) and currently cannot prevent them

If the latter is the case, it seems to me that in the ARM case, we need to re-establish a DNC_Constant to avoid denormal Floats by our own means (like earlier versions of the AudioEngine did). The DNC_Constant then would need to be applied in every "Audio Component" containing Filters.

2021-03-31 08:28 UTC, schlenkibus commented on projects/epc/audio-engine/src/synth/C15Synth.cpp
> +#endif
Should we create a new Issue for this, or do we want to address this in this PR?

2021-03-31 08:28 UTC, schlenkibus approved these changes

2021-03-31 09:25 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/C15Synth.cpp
> +#endif
If it turns out that we need to re-implement something, I would prefer a new issue.

2021-03-31 09:37 UTC, schlenkibus requested changes
In file included from /sources/projects/epc/audio-engine/src/synth/c15-audio-engine/ParallelData.cpp:1:
/sources/projects/epc/audio-engine/src/synth/c15-audio-engine/ParallelData.h:24:20: error: ‘__m128u’ does not name a type; did you mean ‘__m128d’?
   24 | using uint32x4_t = __m128u;
      |                    ^~~~~~~
      |                    __m128d
/sources/projects/epc/audio-engine/src/synth/c15-audio-engine/ParallelData.h:35:5: error: ‘uint32x4_t’ does not name a type; did you mean ‘int32x4_t’?
   35 |     uint32x4_t mmu[simdSize];
      |     ^~~~~~~~~~
      |     int32x4_t
make[2]: *** [projects/epc/audio-engine/CMakeFiles/audio-engine-lib.dir/build.make:362: projects/epc/audio-engine/CMakeFiles/audio-engine-lib.dir/src/synth/c15-audio-engine/ParallelData.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /sources/projects/epc/audio-engine/src/synth/c15-audio-engine/smoother_handle.h:17,
                 from /sources/projects/epc/audio-engine/src/synth/c15-audio-engine/ae_global_section.h:12,
                 from /sources/projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h:21,
                 from /sources/projects/epc/audio-engine/src/synth/C15Synth.h:4,
                 from /sources/projects/epc/audio-engine/src/synth/C15Synth.cpp:1:
/sources/projects/epc/audio-engine/src/synth/c15-audio-engine/ParallelData.h:24:20: error: ‘__m128u’ does not name a type; did you mean ‘__m128d’?
   24 | using uint32x4_t = __m128u;
      |                    ^~~~~~~
      |                    __m128d
/sources/projects/epc/audio-engine/src/synth/c15-audio-engine/ParallelData.h:35:5: error: ‘uint32x4_t’ does not name a type; did you mean ‘int32x4_t’?
   35 |     uint32x4_t mmu[simdSize];
      |     ^~~~~~~~~~
      |     int32x4_t
In file included from /sources/projects/epc/audio-engine/src/synth/c15-audio-engine/smoother_handle.h:17,
                 from /sources/projects/epc/audio-engine/src/synth/c15-audio-engine/ae_global_section.h:12,
                 from /sources/projects/epc/audio-engine/src/synth/c15-audio-engine/ae_global_section.cpp:1:
/sources/projects/epc/audio-engine/src/synth/c15-audio-engine/ParallelData.h:24:20: error: ‘__m128u’ does not name a type; did you mean ‘__m128d’?
   24 | using uint32x4_t = __m128u;
      |                    ^~~~~~~
      |                    __m128d
/sources/projects/epc/audio-engine/src/synth/c15-audio-engine/ParallelData.h:35:5: error: ‘uint32x4_t’ does not name a type; did you mean ‘int32x4_t’?
   35 |     uint32x4_t mmu[simdSize];
      |     ^~~~~~~~~~
      |     int32x4_t
make[2]: *** [projects/epc/audio-engine/CMakeFiles/audio-engine-lib.dir/build.make:388: projects/epc/audio-engine/CMakeFiles/audio-engine-lib.dir/src/synth/c15-audio-engine/ae_global_section.cpp.o] Error 1
make[2]: *** [projects/epc/audio-engine/CMakeFiles/audio-engine-lib.dir/build.make:323: projects/epc/audio-engine/CMakeFiles/audio-engine-lib.dir/src/synth/C15Synth.cpp.o] Error 1

2021-03-31 12:01 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/c15-audio-engine/ParallelData.h
> +using uint32x4_t = __m128u;
sorry, fixed that

2021-03-31 12:23 UTC, merged