Test hw issues
nonlinear-labs-dev/C15 pull request #2726
Opened 2021-07-06 16:52 UTC by schlenkibus

2021-07-07 09:36 UTC, MatthiasSeeber reviewed
UI-wise, the re-introduction of updating HW Return Behavior in the Synth seems solve the primary issue (no moving Mod Amounts on MC Clipping, no Offset when controlling HW Source via MIDI).

However, a Sound Check revealed an issue here, when setting the ReturnBehavior of a Source:

When the UI sends a `HWChangedMessage`, the Synth needs to distinguish between a mere **Position Update** (which should start a Modulation) and a **ReturnBehavior update** (which should only update HW values, not starting a Modulation). Currently, a Modulation is started anytime, causing MC and modulated Param values to jump in Position after setting a connected HW Source to ReturnToCenter.

2021-07-07 09:43 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
> +}
`param->update_behavior` returns a Boolean indicating if the Behavior has changed. This (previously was and) can be used to determine if a Modulation needs to start.

2021-07-07 09:46 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/C15Synth.cpp
>  }
If `m_dsp->updateBehavior` would return the mentioned Boolean, we could pass it to `m_inputEventStage.onUIHWSourceMessage` as an additional argument.

2021-07-07 09:51 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/C15Synth.cpp
>  }
The Boolean would need to be passed down to
``` c++
void dsp_host_dual::onHWChanged(const uint32_t id, float value, const bool returnBehaviorChanged = false)
{
  auto source = m_params.get_hw_src(id);
  const float inc = value - source->m_position;
  source->m_position = value;
  if(returnBehaviorChanged) hwModChain(source, id, inc);
}
```

2021-07-07 12:05 UTC, schlenkibus commented
https://we.tl/t-bOwb3vGEu7

2021-07-07 12:33 UTC, MatthiasSeeber requested changes
The primary issue seems to be fixed. A Sound Check revealed no further issues.

Unfortunately, a new bug seems to have appeared: now, when a Macro Control enters clipping (from TCD, MIDI, WebUI Edit), the HWUI now shows moving Mod Amount Ranges on modulated Parameters. The WebUI shows the Ranges correctly.

2021-07-07 14:44 UTC, schlenkibus commented
last preview build: https://we.tl/t-boPIQVkZY0

2021-07-07 15:25 UTC, MatthiasSeeber approved these changes

2021-07-07 15:26 UTC, merged

2021-07-21 16:15 UTC, hhoegelo commented on projects/epc/playground/src/use-cases/MacroControlParameterUseCases.cpp
> +    , m_mc { parameter }
if base class stores parameter, do we need to store it in derived class, too?

2021-07-21 16:17 UTC, hhoegelo commented on projects/epc/playground/src/use-cases/PedalParameterUseCases.cpp
> +    , m_param { p }
duplicate m_param

2021-07-21 16:17 UTC, hhoegelo commented on projects/epc/playground/src/use-cases/PhysicalControlParameterUseCases.cpp
> +    , m_physicalParam { p }
dup

2021-07-21 16:17 UTC, hhoegelo commented on projects/epc/playground/src/use-cases/RibbonParameterUseCases.cpp
> +    , m_param { p }
mimimi