closes issue #2817
nonlinear-labs-dev/C15 pull request #2823
Opened 2021-09-23 12:56 UTC by schlenkibus

2021-09-23 13:07 UTC, schlenkibus commented
preview build: https://we.tl/t-RDE6saF6UA

2021-09-27 13:22 UTC, MatthiasSeeber requested changes
- [x] Global Local Enable has been renamed (see comment below for a suggestion)
- [x] the Local Enable option still operates with the first iteration of the event flow (the UI-parameters are detached from changes when Local Enable is OFF, though MIDI is sent) - a topic for later
- [x] Panic also sends AllNotesOff (after Panic, a previously held key will still send a NoteOff message when released - I'm not sure if this is a problem or not?)
- [x] AllNotesOff messages seem to be only sent when necessary (Panic, Local Enable = Off, Change in Send Primary Channel, Change in Send Split Channel when in Split Sound, Note Send Routing = Off, Note Local Routing = Off)
- [ ] Reset behavior seems a little odd:
- I cannot observe Reset Messages for PitchBend / Aftertouch when turned to OFF
- likely, every Setting message will always reset the voice allocation and envelopes (as we implemented a while ago - but not matching the ticket requirements)
- some messages (Local Enable, Receive Channels, Note Receive/Local Routings) also reset everything (like Panic does) - which is not necessary and seems to produce glitchy behavior when keys are held (I strongly suspect, that two fade/reset tasks can be fired within one setting message, see second comment)

2021-09-27 13:22 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/C15Synth.cpp
>  }
It seems to me that `handlePressedNotesOnMidiSettingsChanged` may trigger an AllNotesOff Event (which will reset the synth completely - voice alloc, envelopes, buffers). However, in any case `onMidiSettingsReceived` will trigger (possibly another) Reset Event (voice alloc, envelopes).

2021-09-29 08:31 UTC, schlenkibus commented
New Preview: https://we.tl/t-mzxIjaoQj5

2021-09-30 10:28 UTC, davidm2894 commented
bei geladenen Split Sound und Local Enable OFF, wird nur Note On, aber nicht Note Off geschickt

2021-10-06 14:50 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/c15-audio-engine/key_event.h
> +      nltools_assertAlways(keyIdx < Keys);
pls remove

2021-10-06 14:55 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/input/InputEventStage.cpp
> +  nltools::Log::error(__PRETTY_FUNCTION__, "determinedPart:", toString(determinedPart), "primChannel:", (int)mainC,
pls clean up all the traces

2021-10-07 08:44 UTC, merged