Issue 2853
nonlinear-labs-dev/C15 pull request #2874
Opened 2021-10-20 16:43 UTC by schlenkibus

- [x] after install on device: no banks on device anymore

2021-11-04 10:19 UTC, hhoegelo commented on projects/epc/playground/src/Options.cpp
> +void Options::setPresetManagerPath(std::basic_string<char, std::char_traits<char>, std::allocator<char>> basicString)
huh?
std::basic_string<char, std::char_traits<char>, std::allocator<char>> basicString???

2021-11-04 10:20 UTC, hhoegelo commented on projects/epc/playground/src/ParameterId.cpp
> +  //TDOD remove hack
Can the hack already be removed?

2021-11-04 10:24 UTC, hhoegelo commented on projects/epc/playground/src/parameters/HardwareSourceSendParameter.cpp
> +/*
is this comment still needed? Looks like a temporary, private note.

2021-11-04 10:27 UTC, schlenkibus commented on projects/epc/playground/src/Options.cpp
> +void Options::setPresetManagerPath(std::basic_string<char, std::char_traits<char>, std::allocator<char>> basicString)
Oops, I didnt notice that, my IDE seems to refactor std::string to this monstrosity

2021-11-04 10:28 UTC, hhoegelo commented on projects/epc/playground/src/parameters/HardwareSourceSendParameter.h
> + private:
Even if we did not agree on a company wide code style so far, I'd appreciate only one public, protected and private section (in that order) per class. In each sections, I'd prefer methods first, data members second.

2021-11-04 10:34 UTC, hhoegelo commented on projects/epc/playground/src/parameters/ParameterTypes.h
> +using OptRefSettings = std::optional<std::reference_wrapper<Settings>>;
I wonder if an optional reference (with the weird name it introduces) is really any better than just passing a "Settings*" around? To me, "Settings*" would be more clear, because as is now, considerable amounts of the type name describe how (Opt Ref) the type is implemented - where I would expect info about what is actually passed.

2021-11-04 10:40 UTC, hhoegelo commented on projects/epc/playground/src/presets/ParameterGroupSet.cpp
> +  if(isInitialized())
I think this is a code smell. Why would anyone initialize the group set a second time?

2021-11-04 10:50 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/controls/SelectedParameterValue.cpp
> +    switch(newP->getID().getNumber())
I'd like to suggest a little refactoring like this:

if(param)
{
  if(auto setting = getMappingSetting(newP->getID()))
  {
      m_settingConnection = setting->onChange(...);
  }
}

2021-11-04 10:57 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/controls/Slider.h
> +  sigc::connection onParameterSelected(const sigc::slot<void, Parameter*>& cb);
I don't see the necessity for this signal/connection mechanism here. If it is only the PhysicalControlSlider subclass subscribing, it would be enough if the Slider::setParameter(Parameter *param) was virtual and the PhysicalControlSlider would override it.

2021-11-04 11:12 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/PhysicalControlSlider.cpp
> +//  buffer.setColor(FrameBufferColors::C204);
Is this dead code still needed?

2021-11-04 11:17 UTC, hhoegelo commented on projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/PlayControls/SourcesAndAmounts/Sources/PhysicalControlSendParameter.java
> +    //This does not work as I intended, maybe put a event-handler div on top of this control if presenter.isLocalDisabled
Is this still true? If so, is the PR meant to be merged already?

2021-11-04 11:19 UTC, hhoegelo commented on projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/dataModel/editBuffer/EditBufferModel.java
> +		// if (r == null)
Should this dead code be reactivated?

2021-12-06 13:11 UTC, MatthiasSeeber reviewed
## so far working with local off (or routings off)

- [x] hw "receive" params: bound to midi in, bound to synth, ui changes do not trigger midi send
- [x] hw "send" params: bound to lpc, detached from synth, ui changes trigger midi send
- [x] labels and info texts are implemented correctly
- [x] in split sounds, everything seems to work accordingly

## remaining cosmetics

- after boot: when setting local to off, all hw sources send initial midi message?
- currently not reflected: hw return behavior (receive params)
- webui: resizing of hw/amt group when all hw sources are local (no extra column needed in this case)
- webui: update of hidden (or shown) receive params does not work reliably (sometimes, you have to zoom or something to let the ui reflect present receive params correctly)
- hwui: hw source screen currently lacks a mechanism to select between receive and send (webui selection/focus is correctly reflected, though)

## :warning: device loses banks

- already known: after installation of test build, banks are lost - backup your banks beforehand!
- it turns out, banks are lost with every boot: did any directory change or something?
- after fallback to kw-44, banks are persistent again

2021-12-07 11:58 UTC, schlenkibus commented on projects/epc/playground/src/Application.cpp
> +  if(Options::s_acceptanceTests)
This seems suspicous

2021-12-14 11:21 UTC, MatthiasSeeber requested changes
- [ ] Return Behavior is reflected on HW Send Params, however: Return To Center lets Send Param return to Minimum instead of center
- [ ] using the Local Enable option setting it back to On lets the UI always selected Ribbon 2, regardless of what was selected before
- [ ] :warning: **HWUI Crash** HW Source Screen: after setting Local Enable back to On and then pressing Soft Button 1, the Playground crashes

2021-12-15 15:11 UTC, MatthiasSeeber commented on projects/epc/playground/src/parameters/MacroControlParameter.cpp
> +    case C15::PID::MC_A:
:+1:

2021-12-15 15:13 UTC, MatthiasSeeber approved these changes
The mechanism seems solid and functional. Minor cosmetic stuff can be tackled by separate tickets (not bound to A2). The FB Mixer issue seems to have disappeared.

2021-12-15 16:16 UTC, davidm2894 commented
- #2877 ist leider nicht behoben, gibt weiterhin Probleme in der Anzeige. Gefühlt ist es allerdings etwas besser geworden.
- Receive lässt sich über Encoder verstellen, aber eigentlich sollte sich nur Send verstellen lassen. Receive empfängt nur extern oder über MCs (bei bidirektionalen HW Sources).
- Die CCs und die Redo/Undo Pfeile überschneiden sich
- Ribbon LEDs reagieren auch auf Receive Werte. Das Verhalten der Ribbons bei Local Off sollte analog zu dem Verhalten einer physischen HW-Source sein, d.h. bei Local Off reagieren die LEDs nur auf tatsächlichen physischen Einfluss.


Kosmetik: 
- Ich tendiere fast dazu die CCs wieder wegzunehmen, da in der HWUI nicht genug Platz für Pitchbend und Channel Pressure ist und in der WebUI ist es auch sehr eng mit den LSBs. Evtl könnte man den Verweis auf LSB weglassen, also nur die Nummer hinschreiben und Pitchbend (PB) und Channel Pressure (CP) abkürzen. Allerdings kommt ja noch die Problematik mit den Undo-Pfeilen dazu.

2021-12-17 10:38 UTC, MatthiasSeeber approved these changes
Based on the **latest** Test Build (`15bd27e89`):
- [x] MIDI Events, LPC Events, HWUI and WebUI Events (including changing MCs) get handled properly according to HW Param's Local Routing (and for Ribbons their bidirectional binding to MCs) - Local (On) HW and (Off) Receive HW gets displayed and consumed by Synth, (Off) Send gets sent via MIDI Out
- [x] Ribbon LEDs reflect current Routing: Local (On) has LEDs and input bound to normal Receive parameter, (Off) has LEDs and input bound to Send parameter
- [x] Return Behavior: Send parameters reflect current RB correctly and update if RB changed
- later (best put into separate issues beyond A2):
  - cosmetics
    - WebUI: display of rounded corners of HW Sources or in general (as Group frames are already rounded)
    - WebUI+HWUI: HW Source CC Assignment Display refinements (Boled: Undo/Redo collision - WebUI: quite small text - better put into parameter info?)
  - MIDI Out: send updated position of HW Source when Return Behavior changed

2021-12-20 11:11 UTC, davidm2894 commented
Everything seems to work fine!
 
Only thing I noticed is that the WebUI needs quite some time (around 20-30 seconds) to load if you load it for the first time or after a longer break. But I don't know if this is referable to this new feature or my machine, my browser or whatever. Maybe you can test this on your machines.

> WebUI+HWUI: HW Source CC Assignment Display refinements (Boled: Undo/Redo collision - WebUI: quite small text - better put into parameter info?)

Maybe we can put the CCs in the parameter tab of the hardware source? could be a more direct way than the info.

2021-12-22 08:35 UTC, schlenkibus commented on projects/epc/playground/src/parameters/HardwareSourceSendParameter.cpp
> +    : Parameter(pGroup, id, converter, def, coarseDenominator, fineDenominator)
Settings should be reference as it should not be optional

2021-12-22 08:36 UTC, schlenkibus commented on projects/epc/playground/src/parameters/HardwareSourceSendParameter.cpp
> +    : Parameter(pGroup, id, converter, def, coarseDenominator, fineDenominator)
Sibling as well

2021-12-22 08:49 UTC, schlenkibus commented on projects/epc/playground/src/parameters/HardwareSourceSendParameter.cpp
> +{
rename function to better communicate all side effects

2021-12-22 08:51 UTC, schlenkibus commented on projects/epc/playground/src/parameters/HardwareSourceSendParameter.h
> +  PhysicalControlParameter* m_sibling;
move to private parts

2021-12-22 09:12 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/controls/SelectedParameterValue.cpp
> +
consider elseif

2021-12-22 09:12 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/controls/SelectedParameterValue.cpp
> +  if(m_snd)
checks shouldn't be needed

2021-12-22 09:16 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/controls/SelectedParameterValue.h
> +  HardwareSourceSendParameter* m_snd;
Pls initialize

2021-12-22 09:18 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/LocalOffPedalParameterEditLayout2.h
> +#pragma once
looks like crap

2021-12-22 09:20 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/PlayControlParameterLayouts.h
> +  PhysicalControlSlider* m_hwSourceSlider;
pls init

2021-12-22 09:28 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/PhysicalControlSlider.h
> +  HardwareSourceSendParameter* m_snd;
pls init

2021-12-22 09:33 UTC, hhoegelo commented on projects/shared/nltools/include/nltools/logging/Log.h
> +
pls check - maybe can be removed

2021-12-22 09:33 UTC, hhoegelo commented on projects/shared/nltools/include/nltools/messaging/Message.h
> +      bool m_localEnabled;
pls be consistent (m_ or not m_)

2021-12-22 09:34 UTC, hhoegelo commented on projects/shared/nltools/src/nltools/StringTools.cpp
> +    std::string truncate(const std::string& in)
pls rename to 'removeSpaces'

2021-12-22 09:35 UTC, hhoegelo commented on projects/shared/nltools/src/nltools/StringTools.cpp
> +    std::string truncate(const std::string& in)
consider std::copy_if (foo.begin(), foo.end(), std::back_inserter(bar), [](auto i){return ...} );

2021-12-22 09:36 UTC, hhoegelo commented on projects/shared/nltools/src/nltools/StringTools.cpp
> +    std::string truncateNonSpacesAndNonNumbers(const std::string& s)
maybe move or rename

2021-12-22 09:42 UTC, hhoegelo commented on projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/maps/parameters/HardwareCCDisplay.java
> +        super(parent);
Probably this all can be avoided by subscribing and using the according presenter

2021-12-30 15:42 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/input/InputEventStage.cpp
>    }
Maybe the verbose version is more clear to you, so you may just ignore my comment, but this could be simplified to:

if(source != HWChangeSource::UI || m_options->isLocalEnabled(hwID))
  sendHardwareChangeAsMidi(hwID, pos);

2021-12-30 15:51 UTC, hhoegelo approved these changes

2021-12-30 16:39 UTC, merged