Issue 2925
nonlinear-labs-dev/C15 pull request #2927
Opened 2021-11-16 12:17 UTC by schlenkibus

2021-11-16 12:50 UTC, MatthiasSeeber requested changes

2021-11-16 12:50 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
> +}
I would like to advise against that approach.
1. Although this might work in most cases and appears to theoretically produce the desired behavior, we would introduce a new condition (to set the gate release time in stone and never change it). Further, we would settle for tolerating a small statistical chance for this to fail, as the gate release time is almost, but not exactly zero.
2. The operation seems to originate from Acceptance Tests, in which we don't really care about CPU consumption for test helpers. But i don't consider this production-ready code. Summing up all voices is SIMD, so the CPU cost is probably not too much. But still, I don't see a particular benefit here.
3. If an unepxected `VoiceGroup::Invalid` is received, an unitiialized float will be used for the return value.
4. The previous implementations of Reset functionality for Midi Setting changes already established an event-based mechanism for detecting active voices within the InputEventStage. I would prefer using that approach as a base for new preset-and parameter-change- based reset enhancements.

2021-11-16 13:06 UTC, schlenkibus commented on projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
> +}
I understand that using the gate signal is not advised. I changed the implementation to use the prior available `isResetNecessary()`.

2021-11-17 07:42 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
> +  const bool resetDetected = (layerChanged || polyChanged) && resetIsNecessary();
I am absolutely not involved in the topic, but just from the wording I suspect a smell here:
If something is necessary, I would expect it to cause an action, so either there should be an "||" instead of the "&&"' or it should read "resetIsPossible()"?
Please ignore this comment if it doesn't make sense after consideration.

2021-11-17 11:24 UTC, merged