Disable Load from Preset for all HW-Sources and Send Sources + disable Recall Parameter Values
nonlinear-labs-dev/C15 pull request #3041
Opened 2022-02-10 16:18 UTC by schlenkibus

overWrite loadFromPreset for all HW-Sources and Send Sources. Recall Preset Postion is no longer supported in WebUI and Boled for those parameters, closes #3035

2022-02-11 15:30 UTC, MatthiasSeeber requested changes
A few things:
- [ ] The positions won't be recalled anymore, but the Behavior is - and when the Behavior changed, the position will be overwritten. The Behavior should also be ignored on Recall (?).
- [x] ~~(I'm on it) the Audio Engine should also not recall HW Sources anymore (see #3044)~~
- [ ] determine initial state of HW Sources (positions: first PlayController HW event?, behavior: persistent setting?)
- [ ] cleanup: The PresetMessage types (PG --> AE) should also get rid of HW Sources

2022-02-17 08:18 UTC, hhoegelo commented on projects/epc/playground/src/tools/IntrusiveList.h
> +  [[nodiscard]] size_t count() const
Is this new method used anywhere?

2022-02-17 08:26 UTC, hhoegelo commented on projects/epc/playground/src/use-cases/BankUseCases.cpp
> +  EditBufferStorePreparation ebsp(*eb);
Don't we need this in all the siblings as well, i.e. appendEditBuffer, insertEditBufferAsPresetWithUUID etc?

2022-03-14 12:07 UTC, MatthiasSeeber reviewed
Code Review:
- couldn't find anything suspicious (but to be honest, I find it very hard to review due to the complexity)

Trivial:
- acceptance tests failed (I think this is already known)
- webui has display/update problems (when for example changing a return behavior, the amounts will often not directly change their appearance)

Observations:
- Return Behavior
  - [ ] _minor_ changing a behavior will rightfully cause the preset as changed, but storing the changed preset doesn't ask for a new name
  - [x] changing a Source [NonReturn] to [ReturnZero / Center] will set the control position to 0%
  - [ ] _inconsistent_ changing a Source [Return Center] to [NonReturn] will not convert the (bi)polarity, but rather clip the value, so that any negative position will be set to 0%
  - [ ] _unknown_ I cannot observe a HW Amount being converted from "On" / 100% to 50% when changing the correspoding HW Source to [Return Center] ???
- Preset Store
  - [x] returning Sources can be in arbitrary position
- [ ] Preset Recall: several issues (see our drive document)
- Local On/Off: potential Ribbon LED update problem (see our drive document)

2022-03-29 13:43 UTC, schlenkibus commented on projects/epc/playground/src/playground-helpers.cpp
> +    auto symbols = backtrace_symbols(stack.data(), numFrames); //symbols is mallocced here
in order for symbols to be read we need to specify: -rdynamic in the c++ flags

2022-03-30 13:02 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/C15Synth.cpp
> +    auto audioParameterSource = m_dsp->getValueSourceSource(hw);
Consider rename into getLastValueChangeSource

2022-03-30 13:04 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
> +  // todo: rework process
still valid comment?

2022-03-30 13:06 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
> +  // ...
consider removing or filling comment

2022-03-30 13:06 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
> +  //
useless comment

2022-03-30 13:11 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/input/InputEventStage.cpp
> +      // todo: disable midi send?
are todos still valid?

2022-03-30 13:12 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
> +  // todo: rework process
Sorry in general for the occasional sloppy comment, will keep that in mind and review my code accordingly.
In this instance, yes this still is a valid comment, as there are several flaws in the whole initialization procedure. But as this topic also interferes with things like HW Polling, or for example initialized Preset Messages, a corresponding formulated task has not been made yet.

2022-03-30 13:20 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/input/TCDDecoder.cpp
> +    else if(_status == AE_PROTOCOL_CMD)  // PlayController Command
As described, the current code reflects preparations for the HW Polling completion. I admit that the code comments are pretty verbose. I'd like to clean this up when the PlayGround implented the new HW Polling.

2022-03-30 13:27 UTC, hhoegelo commented on projects/epc/playground/src/parameters/HardwareSourceSendParameter.cpp
> +    m_sibling.onLocalEnableChanged(m_isEnabled);
nitpick: pls try to be consistent in using either m_sibling or getSibl....

2022-03-30 13:29 UTC, hhoegelo commented on projects/epc/playground/src/parameters/Parameter.h
> +  virtual QuantizedValue &getValue();
pls remove virtual

2022-03-30 13:32 UTC, hhoegelo commented on projects/epc/playground/src/parameters/PedalParameter.cpp
> +      if(oldMode != newMode && newMode != PedalModes::STAY && initiator == Initiator::EXPLICIT_USECASE)
oldMode has to be different (already tested before)
newMode is m_mode, so you can use that

2022-03-30 13:58 UTC, hhoegelo commented on projects/epc/playground/src/parameters/PedalParameter.cpp
> +    if(isReturning)
consider rephrasing:

getSendParameter()->setCPFromSetting(scope->getTransaction(), getControlPositionValue());
if(isReturning)
  PhysicalControlParameter::setCPFromSetting(scope->getTransaction(), getDefValueAccordingToMode());

2022-03-30 14:06 UTC, hhoegelo commented on projects/epc/playground/src/playground.h
> +  INDIRECT_SETTING_CHANGED
The INDIRECT_SETTING_CHANGED is actually 'write only'. Do we really need it?

2022-03-30 14:08 UTC, hhoegelo commented on projects/epc/playground/src/presets/EditBuffer.cpp
> +std::vector<double> EditBuffer::setHWSourcesToTargetPostion(UNDO::Transaction *transaction)
Isn't his actually setHWSourcesToDefaults ?

2022-03-30 14:10 UTC, hhoegelo commented on projects/epc/playground/src/presets/EditBuffer.cpp
> +        else if(newMode == ReturnMode::Center && oldMode == ReturnMode::None)
do we need this empty branch for documentation purposes or can we just remove it?

2022-03-30 14:10 UTC, hhoegelo commented on projects/epc/playground/src/presets/EditBuffer.cpp
> +  if(!Application::exists())
Do we really need to check here? All the siblings (setHWSourcesToOldPositions ...) don't do it.

2022-03-31 08:38 UTC, hhoegelo commented on projects/epc/playground/src/parameters/PedalParameter.cpp
> +      auto oldMode = m_mode;
oldMode seems to be unused, no?

2022-03-31 10:44 UTC, merged