#3111
nonlinear-labs-dev/C15 pull request #3113
Opened 2022-04-19 15:05 UTC by schlenkibus

enable 'From I/II' for split sounds, cleanup PanelUnitParameterMode to use C15::PIDs instead of hardcoded numbers
closes #3111

2022-04-21 13:10 UTC, schlenkibus commented
- [ ] Parameter Selection Split -> Single keeps From II selected (should go to Effects)
- [ ] Convert Layer -> Split Value is lost and mod-aspects aswell

2022-04-21 14:45 UTC, MatthiasSeeber approved these changes
One tiny thing: When converting Split --> Layer, the From I/II Parameters are correctly transferred (meaning untouched). However, Effects still is selected, which is not necessary (probably left-over from former hiding of parameter).

2022-04-22 07:43 UTC, MatthiasSeeber requested changes
I'm sorry. We again seem to have a very incremental approach to the implementation.
- [x] Convert Split --> Layer: From I/II stays selected, but...
- [x] ... (similar to Layer --> Split), the Parameter's position (and Mod aspects) are lost/defaulted during conversion (which I didn't explicitly mention before)

2022-04-22 07:43 UTC, MatthiasSeeber commented on projects/epc/playground/src/testing/unit-tests/dual-mode-acceptance/UnselectDiabledParameterOnSoundTypeChange.cpp
> +      CHECK(eb->getSelected(VoiceGroup::II)->getID() == ParameterId { 354, VoiceGroup::II });
Just a suggestion: Maybe it would be benefitial/more readable to also use explicit Parameter IDs instead of hard coded values in Test Cases.

2022-05-17 11:00 UTC, MatthiasSeeber approved these changes
:ok:
- deselection non-single to single
- no deselection or reset of pos/mod aspects on split <--> layer
- sound check

:question:
```
acceptance-tests/src/MidiSafeModeTests.cpp:97: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal
```

2022-05-17 11:06 UTC, merged