issue 2836
nonlinear-labs-dev/C15 pull request #3209
Opened 2022-06-08 15:15 UTC by schlenkibus

added sanitize to all set-ops for RoutingSetting, to prevent ReceiveSplit and ReceivePrimary not to be enabled at the same time for all entrys exept notes, those are allowed, closes #2836

2022-06-14 13:23 UTC, schlenkibus commented
- [ ] Test MIDI Clip for Performance Drop
- [ ] MIDI Clip (linked in ticket as: https://github.com/nonlinear-labs-dev/C15/files/7260507/performance_midiclip.mid.zip) is not readable by aplaymidi on linux (performance_midiclip.mid: invalid MIDI data (offset 0x2f))

2022-06-14 13:30 UTC, MatthiasSeeber requested changes
The solution works for

- [x] All Settings On/Off (Primary is chosen)
- [x] enable Primary (whether Split is enabled or not)
- [x] enable Split (when Primary is disabled)

It doesn't work for

- [x] enable Split (when Primary is enabled)

2022-06-14 13:30 UTC, MatthiasSeeber commented on projects/epc/playground/src/device-settings/midi/RoutingSettings.cpp
> +    }
It seems that the User won't be able to enable Receive Split when Receive Primary is enabled.

2022-06-14 14:42 UTC, schlenkibus commented on projects/epc/playground/src/device-settings/midi/RoutingSettings.cpp
> +    }
Good Catch, I fixed this issue.

2022-06-14 15:14 UTC, MatthiasSeeber approved these changes
UI looks good. Now, it depends on a thorough MIDI Test (see above)

2022-06-15 09:11 UTC, davidm2894 commented
UI apparently does not freeze anymore, so this is a step forward. 

Apart from that, we still have the "Rückstau" considering the incoming MIDI data, which is apparently not processed fast enough by the C15, what you can tell by the LEDs that don't stop for quite a while after stopping the MIDI clip. This happens with Single **and** Split Sounds.

Another new issue is that the BOLED has rendering issues on the screens with the modulated parameters. The param stacks are appearing and disappearing constantly. This happens when the MIDI clip is playing **and** only with Split Sounds. 

https://user-images.githubusercontent.com/84857645/173790311-039cf3c3-55a5-430c-9541-f0d664481003.mp4

I will make a new MIDI file with reaper and hopefully you can use this @schlenkibus.

2022-06-15 11:25 UTC, schlenkibus commented
I also tested this midi clip using aplaymidi and my local C15 running (22-16) without any problems.

Maybe we should open a bug report with ableton then?
I will mark this PR as mergeable!

2022-06-15 11:51 UTC, merged