3023
nonlinear-labs-dev/C15 pull request #3263
Opened 2022-08-18 14:51 UTC by schlenkibus

closes #3023, for now without extra symbols and with the textual (off) suffix for pedals instead

@nonlinear-labs is that okay with you for now, that we are not using a new symbol, but rather append the (off) suffix to the parameter name?

- [x] yes, keep it like this
- [ ] yes (for now), but we will add a new symbol later
- [ ] no, wait for a new symbol
- [ ] no, here is the new symbol: (enter link here)
- [ ] no, we don't want this feature anymore

2022-09-07 07:46 UTC, hhoegelo commented on projects/epc/playground/src/parameters/PedalParameter.h
> +  bool m_isHardwareDisabled = false;
what is that boolean used for?

2022-09-07 07:53 UTC, hhoegelo commented on projects/epc/playground/src/groups/HardwareSourcesGroup.cpp
> +  for(auto pedalID : { getPedal1ParameterID(), getPedal2ParameterID(), getPedal3ParameterID(), getPedal4ParameterID() })
I think this could be written more easy to read and less complicated to executed, e.g.:

```suggestion
findAndCastParameterByID<PedalParameter>(getPedal1ParameterID())->init(settings.getSetting("Pedal1Type"));
findAndCastParameterByID<PedalParameter>(getPedal2ParameterID())->init(settings.getSetting("Pedal2Type"));
findAndCastParameterByID<PedalParameter>(getPedal3ParameterID())->init(settings.getSetting("Pedal3Type"));
findAndCastParameterByID<PedalParameter>(getPedal4ParameterID())->init(settings.getSetting("Pedal4Type"));
```


You would not only save a loops and branches here, but also in PedalParameter.

2022-09-07 08:03 UTC, hhoegelo commented on projects/epc/playground/src/parameters/PedalParameter.h
> +  bool m_isHardwareDisabled = false;
MOT: I am not a big fan of this data duplication - in my opinion we should store a reference to the according setting here. The signal connection could just invoke invalidate without changing internal state (onPedalTypeChanged can be dropped then). The getXYZName methods could ask the setting for the current state.

2022-09-07 08:04 UTC, hhoegelo commented on projects/epc/playground/src/groups/HardwareSourcesGroup.cpp
> +HardwareSourcesGroup::~HardwareSourcesGroup()
Do we need a destructor for this class? If so, can we use the default dtor?

2022-09-07 08:06 UTC, hhoegelo commented on projects/epc/playground/src/parameters/PedalParameter.h
> -  using super::super;
The change to an explicit constructor is unnecessary, no?

2022-09-07 08:08 UTC, hhoegelo commented
Sorry I always ignored this PR when I saw (1 of 5 tasks done), only now I noticed that this are not really tasks....

2022-09-07 08:09 UTC, hhoegelo requested changes
see comments

2022-09-07 14:17 UTC, schlenkibus commented
move addParameter from constructor to init()

2022-09-07 14:44 UTC, schlenkibus commented
@hhoegelo fixed-up

2022-09-08 15:32 UTC, hhoegelo approved these changes

2022-09-14 08:25 UTC, merged