Mod rework
nonlinear-labs-dev/C15 pull request #3291
Opened 2022-09-08 14:19 UTC by hhoegelo

2022-09-09 12:32 UTC, schlenkibus commented on projects/epc/playground/src/parameters/ModulateableParameter.cpp
> +  getValue().setRawValue(Initiator::EXPLICIT_PLAYCONTROLLER, newValue);
You dropped the Playcontroller from the function name, maybe it would make sense to change the Initiator to also be EXPLICIT_MACROCONTROL or is there still a distinction?

2022-09-09 12:33 UTC, schlenkibus commented on projects/epc/playground/src/parameters/ModulateableParameter.cpp
> +  auto calcModulationBase = [this] {
why is this a lambda?

2022-09-13 09:04 UTC, schlenkibus commented
The last Issue from this ticket: https://github.com/nonlinear-labs-dev/C15/issues/3286
Is not properly working in this PR. 
@hhoegelo do you thing that is relevant enough to hold back on merging this PR, or is that an seperate issue?

The Upper and Lower Limits of Flanger:AP-Tune are moving when Mod-Amt is 1 St, and the Macro is Moved through the 0-100 range.

2022-09-14 08:26 UTC, MatthiasSeeber reviewed
As mentioned, the Flanger Allpass Tune Modulation behaves odd in the Boled when Amount is 1ST: the amount indicator can disappear, upper/lower limits don't stay constant.

The Split Point modulation isn't right either.

2022-09-28 14:57 UTC, hhoegelo reviewed
pressed the wrong button

2022-09-28 14:57 UTC, hhoegelo commented on projects/epc/playground/src/parameters/ModulateableParameter.cpp
> +  auto calcModulationBase = [this] {
just a matter of style to prefer less state. I did not like

`
float foo = 0;
if(...)
{ 
  foo = ... ;
}

setModulationBase(foo);
`

nor 

`
if(...)
{
   setModulationBase(...);
}
else
{
   setModulationBase(0);
}
`

nor did I want to extract this very private method calcModulationBase().

2022-09-28 14:57 UTC, hhoegelo commented on projects/epc/playground/src/parameters/ModulateableParameter.cpp
> +  auto calcModulationBase = [this] {
sorry, I am too stupid to use the code tag correctly....

2022-09-29 16:16 UTC, schlenkibus approved these changes

2022-10-02 09:22 UTC, MatthiasSeeber requested changes
I wasn't able to test anything yet, see comments.

2022-10-02 09:22 UTC, MatthiasSeeber commented on projects/epc/playground/src/parameters/Parameter.cpp
> +          sendToAudioEngine();
This was and still is highly confusing.

2022-10-02 09:22 UTC, MatthiasSeeber commented on projects/epc/playground/src/parameters/ModulateableParameter.cpp
>  }
The removal of `ModulateableParameter::getModulationSourceAndAmountPacked()` causes testing/unit-tests/ModulateableParameterTests.cpp to fail compilation (I can't compile through with or without Testing and Acceptance-Tests enabled).

```
/home/kleiner-bill/Development/NL/C15/projects/epc/playground/src/testing/unit-tests/ModulateableParameterTests.cpp:25: error: ‘class ModulateableParameter’ has no member named ‘getModulationSourceAndAmountPacked’
/home/kleiner-bill/Development/NL/C15/projects/epc/playground/src/testing/unit-tests/ModulateableParameterTests.cpp: In member function ‘void {anonymous}::____C_A_T_C_H____T_E_S_T____0::test()’:
/home/kleiner-bill/Development/NL/C15/projects/epc/playground/src/testing/unit-tests/ModulateableParameterTests.cpp:25:25: error: ‘class ModulateableParameter’ has no member named ‘getModulationSourceAndAmountPacked’
   25 |     auto packed = peter.getModulationSourceAndAmountPacked();
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I am not sure, but maybe ModulateableParameterTests.cpp is deprecated now, as the packing of Mod Source and Amount into 16 bit is obsolete now? There also is testing/unit-tests/parameters/ModulatedParameterTests.cpp?

2022-10-02 10:32 UTC, MatthiasSeeber commented on projects/epc/playground/src/parameters/ModulateableParameter.cpp
>  }
After removal of the failing code, I can observe the following:

| playground-test | acceptance-tests |
| - | - |
| `All tests passed (22288 assertions in 192 test cases)` | `test cases: 16, 15 passed, 1 failed` |

The acceptance-tests fail is nothing new (SIGSEGV at acceptance-tests/src/MIDI/Issue2831.cpp) though.

Modulation via UI and MIDI seems to work, loading Presets seems to work as well (including returning Sources like the Bender being nonzero at time of recall).

---

Split Point modulation (to be more precise: the display stuff, synth implementation is to follow soon) on its own also seems to behave as intended. However, inconsistencies and buggy behavior appears after Recall.

See the included bank in [mod-rework tests.zip](https://github.com/nonlinear-labs-dev/C15/files/9692239/mod-rework.tests.zip). Presets 001 to 004 have been created during the first review phase of this branch (some time ago), the rest has been created on my test run now. When using the Bender to start a modulation after loading a particular Preset, the "new" Presets seem to show intended behavior. However, the "old" Presets behave badly. A linked Split Point can somehow transform into an overlapping Split Point and vice versa. Have a look at this screen cast for more information.

[Screencast from 02.10.2022 12:13:46.webm](https://user-images.githubusercontent.com/37212609/193449640-df423b99-4ce2-44f6-a05a-9b73c2c82595.webm)

2022-10-02 10:33 UTC, MatthiasSeeber commented
After removal of the failing code, I can observe the following:

| playground-test | acceptance-tests |
| - | - |
| `All tests passed (22288 assertions in 192 test cases)` | `test cases: 16, 15 passed, 1 failed` |

The acceptance-tests fail is nothing new (SIGSEGV at acceptance-tests/src/MIDI/Issue2831.cpp) though.

Modulation via UI and MIDI seems to work, loading Presets seems to work as well (including returning Sources like the Bender being nonzero at time of recall).

---

Split Point modulation (to be more precise: the display stuff, synth implementation is to follow soon) on its own also seems to behave as intended. However, inconsistencies and buggy behavior appears after Recall.

See the included bank in [mod-rework tests.zip](https://github.com/nonlinear-labs-dev/C15/files/9692239/mod-rework.tests.zip). Presets 001 to 004 have been created during the first review phase of this branch (some time ago), the rest has been created on my test run now. When using the Bender to start a modulation after loading a particular Preset, the "new" Presets seem to show intended behavior. However, the "old" Presets behave badly. A linked Split Point can somehow transform into an overlapping Split Point and vice versa. Have a look at this screen cast for more information.

[Screencast from 02.10.2022 12:13:46.webm](https://user-images.githubusercontent.com/37212609/193449640-df423b99-4ce2-44f6-a05a-9b73c2c82595.webm)

2022-10-02 10:52 UTC, hhoegelo commented on projects/epc/playground/src/parameters/ModulateableParameter.cpp
>  }
Yes, ModulateableParameterTests.cpp is obsolete because it tests otherwise unused stuff. I thought that I removed the file but obviously I did not (or I re-introduced it when rebasing / resolving conflicts).

2022-10-06 14:07 UTC, MatthiasSeeber commented
- [x] described Overlap "collapse" or Link "inflate" on Recall seems to be gone now
- [ ] testing? (see table below)
- [ ] I see odd behavior with a minimal mod-amount on some parameters (f.e. Osc Pitch) which reminds me of Split Point rounding?

| acceptance-tests | playground-test |
| - | - |
| `test cases:  40,  38 passed, 2 failed` | `test cases:   191,   190 passed, 1 failed` |
| `assertions: 539, 537 passed, 2 failed` | `assertions: 22288, 22287 passed, 1 failed` |
| `acceptance-tests/src/MidiSafeModeTests.cpp:72: FAILED:` `SIGSEGV` | `testing/unit-tests/presets/ImportPresetManagerTests.cpp:32: FAILED:` `CHECK( memUsage.getUsage() < 9 * 1024 * 1024 ) with expansion:` `9437808 (0x900270) < 9437184 (0x900000)` |
| `acceptance-tests/src/FuzzDecoderTests.cpp:49: FAILED:` `CHECK(testResult) with expansion: false`| |

2022-12-29 11:03 UTC, closed without merging