Issue 3279: extra set of ribbons
nonlinear-labs-dev/C15 pull request #3314
Opened 2022-09-29 12:15 UTC by schlenkibus

closes #3279

2022-09-29 12:19 UTC, schlenkibus commented
@MatthiasSeeber a preview build is currently in the oven!

2022-10-03 19:11 UTC, majjam commented
i tried this build and have two points: 

**First [small bug]:**
**led indicators from a MC with  ribbon 2 will be shown at ribbon4 too and vice versa.** (no 1 to 3 correlation )
1. assign pedal1 to mcA
2. assign ribbon 2 to mcA
3. ribbon 1, 3 and 4 are not assigned anywhere
select boled view of  rib3 and rib 4
led indicators move around when pedal1 is moved

**Second [enhancement]:** 
Additional one proposal from me:
Preset should save the ribbon view position: 3and4 or 1and2 (with default at 1and2-view)
This could save the player one button press in live situations.
Now if i select 3and4 and scroll through some other presets i do see "not assigned" most of the times.

2022-10-04 09:24 UTC, schlenkibus commented
@majjam did you use the build I provided in this thread or did you build your own update?
If you used the .tar provided by me, did you encounter any update-problems?
If so: what version where you running previously?

2022-10-04 10:44 UTC, majjam commented
@schlenkibus  I used the provided build from here.
i did not find any update problems. 
i came from milestone-maintenance  7921e008f194931d5055e816f4494b9827425dfe (before pi4)

2022-10-04 10:58 UTC, schlenkibus commented
> @schlenkibus  I used the provided build from here.
> i did not find any update problems. 
> i came from milestone-maintenance  7921e008f194931d5055e816f4494b9827425dfe (before pi4)
> 
> 

Thank you for the quick response!

2022-10-04 12:37 UTC, MatthiasSeeber requested changes
No Code Review yet, tested via IDE (PG, BBBB, Midi-Over-Ip, AudioEngine).
So far found issues:
- [x] MIDI Settings: this doesn't work reliably. I assigned Rib 3/4 to default Rib 1/2 CCs and they didn't move. After several tryouts, they finally did move when Rib 3 = Rib 1 = CC 24, Rib 4 = Rib 2 = CC 25. Then I reassigned everything to default. Still, Rib 3 and 4 are moving as well
- [ ] Crash in PG and Midi-Over-Ip (see 
[midi-over-ip-crash.txt](https://github.com/nonlinear-labs-dev/C15/files/9706860/midi-over-ip-crash.txt) and 
[playground-crash.zip](https://github.com/nonlinear-labs-dev/C15/files/9706879/playground-crash.zip) - attention, big file)
- [x] Relative Indicator (WebUI ok, Boled/Soled missing)
- [ ] unassigned Ribbons (Soled: dotted lines missing)
- [x] unassigned MCs (unfilled MC symbols, missing)
- [ ] is Ribbon 1/3 in Edit mode working? Hard to say, Soled Screens react accordingly, but does touching and changing the Ribbon control the selected parameter correctly? Via BBBB, the two long Ribbon sliders are useless so via IDE there is no way to verify?
- [x] Ribbon Menus (WebUI, are working - I find it helpful to separate Return Behavior and Absolute/Relative Mode, deviating from the proposal. Maybe, a visual separator would be helpful too?)
- [ ] MC Screen: Soft Button 3 is labeled "more" and leads to a subscreen and back. SB 4 leads to HW Amt Screen (more or less as before) and SB 3 leads back. I'm not sure how consistent this is, but it is working.

2022-10-04 13:20 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.h
> +inline constexpr bool LOG_MIDI_TCD = true;
Cleanup: don't forget to deactivate this before merge.

2022-10-04 13:26 UTC, MatthiasSeeber commented on projects/epc/audio-engine/src/synth/input/InputEventStage.h
> +  constexpr static auto NUM_HW = 10;
:+1:  As mentioned, could be provided by configuration.

2022-10-04 13:42 UTC, schlenkibus commented
- [ ] select modulateable parameter after selecting unmodulateable parameter -> the parameter name is not highlighted

2022-10-05 11:52 UTC, MatthiasSeeber reviewed
So far found:
- :ok: unassigned Ribbons --> dotted Lines in Soled
- Boled, MC Screen: press SB4 twice and the upper right Group Label will indicate changes to the Macro Group (`!Macro Control`), although only the focus was changed?
- the changes to the HW Amounts and removal of several corresponding Screens means that there is no more Parameter Screen for HW Amounts. Consequence: Parameter Info for HW Amounts can only be reached via WebUI (if in HW Amt Mode, the MC Screen could display HW Amount Info instead of MC info)

MIDI Settings
- [ ] still buggy:
assign Ribbon1 to some CC and send something --> Ribbon1 will change, but also Ribbon3 (and even Ribbon4? Similarly, do this with Ribbon2 --> Ribbon4 will change - without any MC Assignments, even if Ribbon 3/4 have no CC set)

unassigned MC --> unfilled Symbol
- [x] MC Boled
- [x] Soled for assigned Ribbon
- [ ] HW Amounts (like "Pedal 1 to MC A") also use filled symbols. Does this apply here as well?

2022-10-05 12:07 UTC, schlenkibus commented
Bezueglich der Filled MC-Symbole in den Routings bin ich ueberfragt, @nonlinear-labs was ist deine Meinung?

MIDI:
Test auf meinem Device: 
Ribbon 1: CC18
Ribbon 2: CC25
Ribbon 3: CC26
Ribbon 4: CC27

Ich habe den Ribbon 1 ueber die HW bewegt und auf meinen PC einen Midi-Clip aufgenommen.
Wenn ich den Clip replaye bewegt sich ribbon 1 wie erwartet. Auch das umschalten auf Ribbon 3/4 fuehrt zu den gewuenschten Ergebnissen: Ribbon 3 und 4 bewegen sich nicht.

2022-10-05 12:24 UTC, MatthiasSeeber commented
Hier, die vier Pedale sind genauso assigned wie die vier Ribbons. Ich gehe die CCs 20 ... 23 nacheinander durch. Ich habe diesmal midi-over-ip nicht mit dabei, vorher lief das bei mir immer mit..

[Screencast from 05.10.2022 14:22:49.webm](https://user-images.githubusercontent.com/37212609/194059498-6f5480e0-3e46-437a-a73b-6199fc414845.webm)

2022-10-05 12:52 UTC, davidm2894 commented
- changing mode of one ribbon to relative has impact on both ribbons of this ribbon pair. I assume that the mode of the physical ribbon not the virtual ribbon is changed. when changed back to absolute mode, the LED ribbons of the second ribbon show the position of the first ribbon (if second ribbon of a pair is selected)
- the superscripted "r" is quite small and for the readability it would be better to leave the pixel in top left corner blank. Is this a symbol from the font?
- if you change the MC parameter of a MC connected to one of the ribbons of the second pair (2/4), both ribbons move.
- CC XX misses for ribbons 3/4 in HW Source Screen
- the HW Sel field in MC screen shows the superscripted "r", it would be better if it's not shown in this place

2022-10-06 16:35 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/input/InputEventStage.cpp
> +  if(hwID == HardwareSource::RIBBON3)
consider introducing a translateXtoY method

2022-10-06 16:41 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/input/TCDDecoder.cpp
> +      keyOrController = channel;
consider m_ for members

2022-10-06 16:47 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/input/TCDDecoder.cpp
> +      keyOrController = channel;
keyOrController should be called m_key and not be assigned if tcd message is not a key (maybe make it an optional or have a special INVALID value?)

2022-10-06 17:05 UTC, hhoegelo commented on projects/epc/playground/src/use-cases/EditBufferUseCases.cpp
> +void EditBufferUseCases::selectLastSelectedMacroControlParameter()
unused?

2022-10-06 17:05 UTC, hhoegelo commented on projects/epc/playground/src/presets/EditBuffer.cpp
> +ParameterId EditBuffer::getLastSelectedMacroId() const
unused?

2022-10-06 17:06 UTC, hhoegelo commented on projects/epc/playground/src/presets/EditBuffer.cpp
> +    , m_lastSelectedMacroControl { C15::PID::MC_A, VoiceGroup::Global }
unused?

2022-10-06 17:13 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/base-unit/LowerRibbon.cpp
> +        HardwareSourcesGroup::getLowerRibbonParameterID());
consider being consistent with getLowerRibbon4ParameterID

2022-10-06 17:16 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/base-unit/UpperRibbon.cpp
> +        HardwareSourcesGroup::getUpperRibbonParameterID());
consistent naming

2022-10-06 17:29 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/base-unit/soled/SelectedRibbonsIndication.cpp
> +void drawDottedLine(FrameBuffer& fb, int l, int t, int lenght)
typo length

2022-10-06 17:30 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/base-unit/soled/SelectedRibbonsIndication.cpp
> +  return ribbon->getCurrentModulatingMacroControlString() != "not assigned";
this smells

2022-10-06 17:35 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/descriptive-layouts/LayoutFactory.cpp
> +  Layout* BoledLayoutFactory::instantiate(FocusAndMode fam)
investigate: whats motivation to return raw pointer here?

2022-10-06 17:39 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.cpp
> +    nltools::Log::error(toString(p->getMode()));
is that really an error?

2022-10-06 17:41 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.h
> +  struct InitialParameterSelection {
huh?

2022-10-06 17:41 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/MacroControlParameterLayouts.h
> +  std::optional<InitialParameterSelection> m_initialParameterSelection = std::nullopt;
huh?

2022-10-06 17:53 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/HWSourceAmountCarousel.cpp
> +    doTurn(0);
pls check if doTurn(0) actually does something (also in turn())

2022-10-06 18:06 UTC, hhoegelo commented on projects/epc/playground/src/proxies/playcontroller/PlaycontrollerProxy.cpp
> +      case 8:  //meh
Pls try to not use Playcontroller Domain enum in Audioengineproxy context

2022-10-07 09:39 UTC, davidm2894 commented
I had a crash with the Preview Build from this PR. Error Journal is attached and was downloaded just right after the crash. Banks were reloaded and sound was gone for a moment. 

[C15-journal.tar.gz.txt](https://github.com/nonlinear-labs-dev/C15/files/9732729/C15-journal.tar.gz.txt)

2022-10-11 09:03 UTC, schlenkibus commented on projects/epc/playground/src/use-cases/EditBufferUseCases.cpp
> +void EditBufferUseCases::selectLastSelectedMacroControlParameter()
still used!

2022-10-13 16:37 UTC, hhoegelo approved these changes

2022-10-13 16:37 UTC, merged