Issue 2995 UI
nonlinear-labs-dev/C15 pull request #3435
Opened 2022-12-15 11:03 UTC by schlenkibus

2022-12-22 16:08 UTC, MatthiasSeeber approved these changes
I think I can give general approval, although I only tested Boled and WebUI (no code review). A few remarks:
- #3438: HWUI seems OK, WebUI is missing (as anticipated - we may close this issue with this PR and later reopen it, or make a new one for WebUI stuff)
  - also: the FB Mixer Logic for arrows (Level > -inf AND FX Channel != 0) could also be used in similar fashion for the Output Mixer for arrows (Level > -inf AND Any Channel != 0)
- #3442: i assume it is correct now?
- #3443: no type entry in HWUI/WebUI, but:
  - HWUI shows `u`/`m` in Name, but no Split/Layer symbol in name field
  - WebUI shows neither
- #3444: i assume it is correct now? (the label in focus is colored white)

2023-01-02 14:39 UTC, MatthiasSeeber requested changes
When converting a typical Single Sound (Master > FX Mix: 0%) into Split/Layer, the UI correctly shows that Part II Volume is at -inf. But both Parts are audible and changing Part II Volume has no effect. Changing Part I Volume affects both Parts. This is not the case when loading already existing Split/Layer presets.

2023-01-03 10:00 UTC, schlenkibus commented
> * #3443: no type entry in HWUI/WebUI, but:
>   
>   * HWUI shows `u`/`m` in Name, but no Split/Layer symbol in name field
>   * WebUI shows neither

- [x] the hwui Preset-Info Screen shows the type of the preset in the header like this; Preset (Layer), this is fine
- [ ] the webui does not have this kind of info, i will add that

2023-01-03 11:59 UTC, MatthiasSeeber commented
Another thing: converting a Single Sound to Split/Layer resets Master Serial FX and FX Pan?

2023-01-04 14:48 UTC, hhoegelo commented on projects/epc/audio-engine/src/synth/c15-audio-engine/dsp_host_dual.cpp
> +        // todo: Fx Mix
is this todo still relevant?

2023-01-04 15:27 UTC, hhoegelo commented on projects/epc/playground/src/groups/ParameterGroup.cpp
>      polyCount += isPolyParam;
the counts are write-only

2023-01-04 15:51 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/SingleSoundPolyToFXIndicator.h
> +  Control* polyToFx;
please initialize members properly

2023-01-04 15:51 UTC, hhoegelo commented on projects/epc/playground/src/proxies/hwui/descriptive-layouts/concrete/sound/SingleSoundPolyToFXIndicator.h
> +  Control* label1;
please initialize members properly

2023-01-04 15:59 UTC, hhoegelo commented on projects/epc/playground/src/serialization/RecallEditBufferSerializer.cpp
> +        param->m_ribbonTouchBehaviour = RibbonTouchBehaviour::NUM_TOUCH_BEHAVIOURS;
I would have expected a 'default' touch behavior instead of an invalid one?

2023-01-04 16:00 UTC, hhoegelo commented on projects/epc/playground/src/serialization/RecallEditBufferSerializer.cpp
> +            split->m_ribbonTouchBehaviour = RibbonTouchBehaviour::NUM_TOUCH_BEHAVIOURS;
I would have expected a 'default' touch behavior instead of an invalid one?

2023-01-04 16:00 UTC, hhoegelo commented on projects/epc/playground/src/testing/unit-tests/ParameterTests.cpp
> +//TODO FIX this test!!! isGlobal now depends on SoundType!!
Is the comment still valid and if so, can the todo be resolved?

2023-01-04 16:06 UTC, hhoegelo commented on projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/presenters/ParameterPresenterProviders.java
> +			//TODO implement get real Parameter by type? and soundtype -> see (EditBuffer::getSelected())
is todo still relevant?

2023-01-05 10:32 UTC, merged