proposed new set of rules to prevent FX-Disabled display if Fx-FB is used
nonlinear-labs-dev/C15 pull request #3489
Opened 2023-01-10 15:18 UTC by schlenkibus

closes #3465

2023-01-11 09:46 UTC, MatthiasSeeber requested changes
I'm afraid we first need to formulate the rules adequately before providing an implementation.

https://github.com/nonlinear-labs-dev/C15/issues/3465#issuecomment-1378471552 is also a valid point, indicating that the algorithm is still premature.

2023-01-11 09:46 UTC, MatthiasSeeber commented on projects/epc/playground/src/proxies/hwui/panel-unit/boled/parameter-screens/controls/VoiceGroupIndicator.cpp
> +  return fx_mix_cond && !((serial_fx_cond || (from_fx_cond && fb_fx_cond)) && (to_fx_cond || fb_is_used));
I think the algorithm is not mature yet.
If for example the `fx_mix_cond` is false, the whole expression results to false, meaning that the corresponding FX are used - which is not the intention I think.

2023-01-13 09:49 UTC, MatthiasSeeber approved these changes
This looks and feels pretty solid:
- known scenarios that didn't work before now work reliably, I couldn't find any situations in which the indicators were wrong
- in both UIs, the indicators always seem up-to-date (including modulation)
- no unexpected failing tests

2023-01-19 15:28 UTC, hhoegelo commented on projects/web/static/nonmaps/src/main/java/com/nonlinearlabs/client/world/overlay/Overlay.java
> +	private class SingleSoundFX_II_Unused extends SingleSoundFX_I_Unused
I'd prefer the logic to be moved into EditBufferPresenterPorovider and the result into EditBufferPresenter.
The class hierarchy "SingleSoundFX_II_Unused" is a "SingleSoundFX_I_Unused" also looks a bit like the "LargeLabel" is a "SmallLabel" that we are constantly wondering about. I'd prefer to have a base class for both, if this is still needed after using presenters.

2023-01-19 18:17 UTC, merged