Issue 3497
nonlinear-labs-dev/C15 pull request #3511
Opened 2023-01-12 09:40 UTC by schlenkibus

implement more load-to-part rules according to #3497 

closes #3497

2023-01-13 16:50 UTC, MatthiasSeeber requested changes
Unfortunately, the provided rules are still ambiguous in some places and lead to some misunderstandings: In the Feedback Mixer, the Level reductions of Channels apply to the values of the Source Preset. In this PR, the Target Preset's Levels are reduced instead.

Besides, the level reduction rules are currently worked out in more detail. I hope to be able to provide an unambiguous and full spec next week.

2023-01-18 10:58 UTC, MatthiasSeeber approved these changes
I couldn't find anything suspicious, it seems to work as expected.
Due to big changes in the Playground, it may be beneficial to have a code-review from someone more qualified?

2023-01-18 16:03 UTC, hhoegelo commented on projects/epc/playground/src/presets/EditBuffer.cpp
> +  //undoableResetCrossPartFXParametersForLoadToPartIntoLayer(transaction, copyTo);
do we need this dead code?

2023-01-18 16:04 UTC, hhoegelo approved these changes

2023-01-19 15:13 UTC, merged