Change backup filename
nonlinear-labs-dev/C15 pull request #3812
Opened 2023-06-27 09:44 UTC by schlenkibus

2023-06-27 10:03 UTC, MatthiasSeeber commented on projects/shared/configuration/process.sh
> +isDevPC=$3
This was recently removed, as the parameter is unused within the script.
Is there a reason for this parameter, as it still is unused?

2023-06-27 10:04 UTC, MatthiasSeeber commented on projects/shared/configuration/build-in-docker.sh
> +  /bin/bash "$sourceDir"/process.sh "$sourceDir" "$binaryDir"
process.sh is called without the introduced `isDevPC` parameter?

2023-06-27 10:12 UTC, MatthiasSeeber requested changes
tested webui only
- [x] new backup exports produce new .nlbackup file format
- [x] old .xml.tar.gz and new .nlbackup files can be imported
- [ ] support for zip files seems to be broken now (file type is not included in supported types and will not be visible in dialog, when changing dialog to show all files and selecting a .zip backup, this will result in an error message)

2023-06-27 13:48 UTC, MatthiasSeeber approved these changes
tested restore/save in WebUI (download) and BBBB (usb-stick) on ubuntu
- [x] save provides working `.nlbackup`
- [x] restore works with all three file formats (`.xml.zip`, `.xml.tar.gz`, `.nlbackup`), also file filter works as intended (showing all supported types by default)
- currently unclear: WebUI provides `[timestamp]-nonlinear-c15-banks.nlbackup`, whereas BBBB provides `[timestamp]-c15-banks.nlbackup`

2023-06-28 09:38 UTC, hhoegelo approved these changes

2023-06-28 11:22 UTC, merged