BOLED: fix Voices-Screen incorrectly updates on Sound-Type change
nonlinear-labs-dev/C15 pull request #3850
Opened 2023-08-09 09:42 UTC by schlenkibus

original bug-report:
```
Bug:
Voices-Screen hat I/II Button (der auch funktioniert), wenn man von Single Sound auf Layer Sound wechselt (sic. ueber WebUI)
```

2023-08-09 11:41 UTC, MatthiasSeeber requested changes
:warning: The Sound Screen is broken. Pressing the Sound button (no matter which Sound Type) in the bbbb-ui application leads to the following screen:

![boled-sound-deprecated](https://github.com/nonlinear-labs-dev/C15/assets/37212609/ee75b8dc-23b6-4465-96be-daa601f807b7)

2023-08-09 13:22 UTC, MatthiasSeeber approved these changes
With the Command Line Argument `-l` _(path/to/C15/package/c15-playground/resources)_, the Sound Screen is available and the Voices Screen doesn't show a Soft Button I/II when in a Single or Layer Sound.

2023-08-10 09:18 UTC, hhoegelo commented on package/c15-playground/src/hwui/descriptive-layouts/ConditionRegistry.cpp
> +    m_signal.send();
maybe this could be a problem?

2023-08-10 09:19 UTC, hhoegelo commented on package/c15-playground/src/hwui/descriptive-layouts/ControlInstance.cpp
> +  {
consider using std::tie(foo, bar) == std::tie(other.foo, other.bar);

2023-08-10 11:09 UTC, hhoegelo approved these changes

2023-08-10 11:09 UTC, merged