Rework Syncing on Splitpoints
nonlinear-labs-dev/C15 pull request #3966
Opened 2023-12-20 07:28 UTC by hhoegelo

The splitpoint syncing was implemented as device setting, but actually it is a property of the sound/preset.

2023-12-20 16:44 UTC, schlenkibus requested changes
I want to have a look into the deleted `StoreHelper` and the potential crash in the SplitParameterEditLayout

2023-12-20 16:44 UTC, schlenkibus commented on package/c15-playground/src/hwui/descriptive-layouts/events/event-sources/edit-buffer/EditBufferEvents.cpp
> +void DescriptiveLayouts::SplitPointsAreUnsyncedButNextToEachOther::onSettingChanged(const Setting *s)
`SplitPointsAreUnsyncedButNextToEachOther::onSettingChanged` is no longer used

2023-12-20 16:44 UTC, schlenkibus commented on package/c15-playground/src/hwui/panel-unit/boled/parameter-screens/ModulateableDualVoiceGroupMasterAndSplitPointLayout.cpp
> +  Application::get().getPresetManager()->getEditBuffer()->onChange(
this still looks like it could lead to a crash

2023-12-20 16:44 UTC, schlenkibus commented on package/c15-playground/src/testing/unit-tests/parameters/SplitPointTests.cpp
> +      CHECK(sI->areSplitPointsNextToEachOther());
just a comment: I really like the new names for the sync-related functions, makes it so much easier to grasp what is going on!

2023-12-20 16:44 UTC, schlenkibus commented on package/playground-lib/src/presets/EditBuffer.cpp
> +      //TODO implement rules to copy ModAspects from I into II or vice versa
I know that you copied that comment over from the former use-case, but do you know what we should make of that?

2023-12-20 16:44 UTC, schlenkibus commented on package/playground-lib/src/use-cases/BankUseCases.cpp
> -  StoreUseCaseHelper::onStore(transaction, *preset, *pm, m_settings);
Why was this removed completly? are we sure we no-longer want to call `PresetManager::onPresetStored();` which used to happen in StoreUseCaseHelper, now we no longer send a signal...

2023-12-21 10:16 UTC, hhoegelo commented on package/c15-playground/src/hwui/panel-unit/boled/parameter-screens/ModulateableDualVoiceGroupMasterAndSplitPointLayout.cpp
> +  Application::get().getPresetManager()->getEditBuffer()->onChange(
well spotted!

2023-12-21 14:13 UTC, merged